### ISSUE TITLE
Create a Bower package

### ISSUE THREAD

**Issue by DiegoLopesLima** [DiegoLopesLima/warble#10]

**Comment by willycamargo** [comment]
Is it necessary? I think the most projects are creating just npm package and sometimes host it on CDN.

You can see it to understand what I think: https://www.quora.com/Is-Bower-dying

**Comment by DiegoLopesLima** [comment]
Actually, I'm really thinking of abort this task.
Very thanks for your comment.
I'll remove from the project soon.
